version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: ag
      POSTGRES_DB: questions_answers
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - qa_volume:/usr/share/app
    ports:
      - '5432:5432'
    healthcheck:
      test: "exit 0"
  server:

volumes:
  qa_volume:
    driver: local
    driver_opts:
        o: bind
        type: none
        device: /home/ubuntu/csv_data
networks:
  default:
    external:
      name: sdc